openjdk-8/openjre-8: skip the dev-so test
Fixed:
ERROR: QA Issue: non -dev/-dbg/nativesdk- package contains symlink .so:
openjdk-8 path
'work/core2-64-poky-linux/openjdk-8/72b05-r0/packages-split/openjdk-8/usr/lib/jvm/openjdk-8/jre/lib/amd64/server/libjsig.so'
[dev-so]

The symlink .so is valid so we just skip the test
just like what we does in openjdk-7.

(LOCAL REV: NOT UPSTREAM) -- Sent to oe-devel on 20151222

Signed-off-by: Jackie Huang <jackie.huang@windriver.com>