meta-java: allow empty packages generated
This issue is found during installing the ovp-ovirt-engine full development
and debug files via wr-installer, see anaconda.log:

Traceback (most recent call first):
  File "/usr/lib64/python2.7/site-packages/smart/backends/rpm/pm.py",
line 231, in commit
    raise Error, "\n".join(problines)
  File "/usr/lib64/python2.7/site-packages/smart/control.py", line 749,
in commitChangeSet
    pmclass().commit(pmcs, pkgpaths)
  File "/usr/lib64/python2.7/site-packages/smart/control.py", line 681,
in commitTransaction
    return self.commitChangeSet(trans.getChangeSet(), caching, confirm)
  File "/usr/lib64/python2.7/site-packages/smart/commands/install.py",
line 207, in main
    ctrl.commitTransaction(trans, confirm=confirm)
  File "/usr/lib64/python2.7/site-packages/smart/interface.py", line 53,
in run
    result = _command.main(self._ctrl, opts)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/smartinstall.py",
line 570, in runSmart
    rc = iface.run(command, argv)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/smartinstall.py",
line 895, in doInstall
    self.anaconda.backend.asmart.runSmart('install',
comp_pkgs_to_attempt)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/backend.py", line
206, in doInstall
    return anaconda.backend.doInstall(anaconda)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/dispatch.py", line
373, in dispatch
    self.dir = self.steps[self.step].target(self.anaconda)
  File "/usr/lib64/python2.7/site-packages/pyanaconda/dispatch.py", line
241, in go_forward
    self.dispatch()
  File "/usr/lib64/python2.7/site-packages/pyanaconda/gui.py", line
1201, in nextClicked
    self.anaconda.dispatch.go_forward()
Error: commons-logging-dev-1.1.1-r0.1.0 requires commons-logging =
1.1.1-r0.1.0

${PN}-dev.rpm requires ${PN}.rpm, but if ${PN}.rpm is empty, it
won't be produced by default, so the installation exception shows up.
Adding ALLOW_EMPTY_${PN} in their bb files will make sure the empty
package are generated.

The effected packages are commons-logging, junit4, gnumail, gnujaf,
avalon-framework-api, oro, servlet2.3, logkit, inetlib and log4j1.2.

(LOCAL REV: NOT UPSTREAM) -- Pending

Signed-off-by: Yunguo Wei <yunguo.wei@windriver.com>
Signed-off-by: Amy Fong <amy.fong@windriver.com>
Signed-off-by: Jackie Huang <jackie.huang@windriver.com>